/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.agents.instructions.credentials.requests;

import com.basistheory.core.ObjectMappers;
import com.basistheory.types.AgenticMerchant;
import com.basistheory.types.Amount;
import com.basistheory.types.DeliveryMethod;
import com.basistheory.types.Product;
import com.basistheory.types.ShippingAddress;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetCredentialsRequest.Builder.class)
public final class GetCredentialsRequest {
    private final Optional<List<Product>> products;

    private final AgenticMerchant merchant;

    private final Optional<Amount> amount;

    private final Optional<DeliveryMethod> deliveryMethod;

    private final Optional<ShippingAddress> shippingAddress;

    private final Map<String, Object> additionalProperties;

    private GetCredentialsRequest(
            Optional<List<Product>> products,
            AgenticMerchant merchant,
            Optional<Amount> amount,
            Optional<DeliveryMethod> deliveryMethod,
            Optional<ShippingAddress> shippingAddress,
            Map<String, Object> additionalProperties) {
        this.products = products;
        this.merchant = merchant;
        this.amount = amount;
        this.deliveryMethod = deliveryMethod;
        this.shippingAddress = shippingAddress;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("products")
    public Optional<List<Product>> getProducts() {
        return products;
    }

    @JsonProperty("merchant")
    public AgenticMerchant getMerchant() {
        return merchant;
    }

    @JsonProperty("amount")
    public Optional<Amount> getAmount() {
        return amount;
    }

    @JsonProperty("delivery_method")
    public Optional<DeliveryMethod> getDeliveryMethod() {
        return deliveryMethod;
    }

    @JsonProperty("shipping_address")
    public Optional<ShippingAddress> getShippingAddress() {
        return shippingAddress;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetCredentialsRequest && equalTo((GetCredentialsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetCredentialsRequest other) {
        return products.equals(other.products)
                && merchant.equals(other.merchant)
                && amount.equals(other.amount)
                && deliveryMethod.equals(other.deliveryMethod)
                && shippingAddress.equals(other.shippingAddress);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.products, this.merchant, this.amount, this.deliveryMethod, this.shippingAddress);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MerchantStage builder() {
        return new Builder();
    }

    public interface MerchantStage {
        _FinalStage merchant(@NotNull AgenticMerchant merchant);

        Builder from(GetCredentialsRequest other);
    }

    public interface _FinalStage {
        GetCredentialsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage products(Optional<List<Product>> products);

        _FinalStage products(List<Product> products);

        _FinalStage amount(Optional<Amount> amount);

        _FinalStage amount(Amount amount);

        _FinalStage deliveryMethod(Optional<DeliveryMethod> deliveryMethod);

        _FinalStage deliveryMethod(DeliveryMethod deliveryMethod);

        _FinalStage shippingAddress(Optional<ShippingAddress> shippingAddress);

        _FinalStage shippingAddress(ShippingAddress shippingAddress);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MerchantStage, _FinalStage {
        private AgenticMerchant merchant;

        private Optional<ShippingAddress> shippingAddress = Optional.empty();

        private Optional<DeliveryMethod> deliveryMethod = Optional.empty();

        private Optional<Amount> amount = Optional.empty();

        private Optional<List<Product>> products = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetCredentialsRequest other) {
            products(other.getProducts());
            merchant(other.getMerchant());
            amount(other.getAmount());
            deliveryMethod(other.getDeliveryMethod());
            shippingAddress(other.getShippingAddress());
            return this;
        }

        @java.lang.Override
        @JsonSetter("merchant")
        public _FinalStage merchant(@NotNull AgenticMerchant merchant) {
            this.merchant = Objects.requireNonNull(merchant, "merchant must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage shippingAddress(ShippingAddress shippingAddress) {
            this.shippingAddress = Optional.ofNullable(shippingAddress);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "shipping_address", nulls = Nulls.SKIP)
        public _FinalStage shippingAddress(Optional<ShippingAddress> shippingAddress) {
            this.shippingAddress = shippingAddress;
            return this;
        }

        @java.lang.Override
        public _FinalStage deliveryMethod(DeliveryMethod deliveryMethod) {
            this.deliveryMethod = Optional.ofNullable(deliveryMethod);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "delivery_method", nulls = Nulls.SKIP)
        public _FinalStage deliveryMethod(Optional<DeliveryMethod> deliveryMethod) {
            this.deliveryMethod = deliveryMethod;
            return this;
        }

        @java.lang.Override
        public _FinalStage amount(Amount amount) {
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "amount", nulls = Nulls.SKIP)
        public _FinalStage amount(Optional<Amount> amount) {
            this.amount = amount;
            return this;
        }

        @java.lang.Override
        public _FinalStage products(List<Product> products) {
            this.products = Optional.ofNullable(products);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "products", nulls = Nulls.SKIP)
        public _FinalStage products(Optional<List<Product>> products) {
            this.products = products;
            return this;
        }

        @java.lang.Override
        public GetCredentialsRequest build() {
            return new GetCredentialsRequest(
                    products, merchant, amount, deliveryMethod, shippingAddress, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
