/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.agents.instructions;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.agents.instructions.credentials.AsyncCredentialsClient;
import com.basistheory.resources.agentic.agents.instructions.requests.CreateInstructionRequest;
import com.basistheory.resources.agentic.agents.instructions.requests.InstructionsListRequest;
import com.basistheory.resources.agentic.agents.instructions.requests.UpdateInstructionRequest;
import com.basistheory.resources.agentic.agents.instructions.verify.AsyncVerifyClient;
import com.basistheory.types.Instruction;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncInstructionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawInstructionsClient rawClient;

    protected final Supplier<AsyncCredentialsClient> credentialsClient;

    protected final Supplier<AsyncVerifyClient> verifyClient;

    public AsyncInstructionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawInstructionsClient(clientOptions);
        this.credentialsClient = Suppliers.memoize(() -> new AsyncCredentialsClient(clientOptions));
        this.verifyClient = Suppliers.memoize(() -> new AsyncVerifyClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawInstructionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public CompletableFuture<SyncPagingIterable<Instruction>> list(String agentId) {
        return this.rawClient.list(agentId).thenApply(response -> response.body());
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public CompletableFuture<SyncPagingIterable<Instruction>> list(String agentId, RequestOptions requestOptions) {
        return this.rawClient.list(agentId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public CompletableFuture<SyncPagingIterable<Instruction>> list(String agentId, InstructionsListRequest request) {
        return this.rawClient.list(agentId, request).thenApply(response -> response.body());
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public CompletableFuture<SyncPagingIterable<Instruction>> list(
            String agentId, InstructionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(agentId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a new payment instruction for an agent, linked to an enrollment.
     */
    public CompletableFuture<Instruction> create(String agentId, CreateInstructionRequest request) {
        return this.rawClient.create(agentId, request).thenApply(response -> response.body());
    }

    /**
     * Create a new payment instruction for an agent, linked to an enrollment.
     */
    public CompletableFuture<Instruction> create(
            String agentId, CreateInstructionRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(agentId, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> get(String agentId, String instructionId) {
        return this.rawClient.get(agentId, instructionId).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> get(String agentId, String instructionId, RequestOptions requestOptions) {
        return this.rawClient.get(agentId, instructionId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String agentId, String instructionId) {
        return this.rawClient.delete(agentId, instructionId).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String agentId, String instructionId, RequestOptions requestOptions) {
        return this.rawClient.delete(agentId, instructionId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> update(String agentId, String instructionId) {
        return this.rawClient.update(agentId, instructionId).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> update(String agentId, String instructionId, RequestOptions requestOptions) {
        return this.rawClient.update(agentId, instructionId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> update(
            String agentId, String instructionId, UpdateInstructionRequest request) {
        return this.rawClient.update(agentId, instructionId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Instruction> update(
            String agentId, String instructionId, UpdateInstructionRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .update(agentId, instructionId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public AsyncCredentialsClient credentials() {
        return this.credentialsClient.get();
    }

    public AsyncVerifyClient verify() {
        return this.verifyClient.get();
    }
}
