/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.agents.instructions;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.agents.instructions.credentials.CredentialsClient;
import com.basistheory.resources.agentic.agents.instructions.requests.CreateInstructionRequest;
import com.basistheory.resources.agentic.agents.instructions.requests.InstructionsListRequest;
import com.basistheory.resources.agentic.agents.instructions.requests.UpdateInstructionRequest;
import com.basistheory.resources.agentic.agents.instructions.verify.VerifyClient;
import com.basistheory.types.Instruction;
import java.util.function.Supplier;

public class InstructionsClient {
    protected final ClientOptions clientOptions;

    private final RawInstructionsClient rawClient;

    protected final Supplier<CredentialsClient> credentialsClient;

    protected final Supplier<VerifyClient> verifyClient;

    public InstructionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawInstructionsClient(clientOptions);
        this.credentialsClient = Suppliers.memoize(() -> new CredentialsClient(clientOptions));
        this.verifyClient = Suppliers.memoize(() -> new VerifyClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawInstructionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public SyncPagingIterable<Instruction> list(String agentId) {
        return this.rawClient.list(agentId).body();
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public SyncPagingIterable<Instruction> list(String agentId, RequestOptions requestOptions) {
        return this.rawClient.list(agentId, requestOptions).body();
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public SyncPagingIterable<Instruction> list(String agentId, InstructionsListRequest request) {
        return this.rawClient.list(agentId, request).body();
    }

    /**
     * List all purchase instructions for an agent with cursor-based pagination and optional enrollment filter.
     */
    public SyncPagingIterable<Instruction> list(
            String agentId, InstructionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(agentId, request, requestOptions).body();
    }

    /**
     * Create a new payment instruction for an agent, linked to an enrollment.
     */
    public Instruction create(String agentId, CreateInstructionRequest request) {
        return this.rawClient.create(agentId, request).body();
    }

    /**
     * Create a new payment instruction for an agent, linked to an enrollment.
     */
    public Instruction create(String agentId, CreateInstructionRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(agentId, request, requestOptions).body();
    }

    public Instruction get(String agentId, String instructionId) {
        return this.rawClient.get(agentId, instructionId).body();
    }

    public Instruction get(String agentId, String instructionId, RequestOptions requestOptions) {
        return this.rawClient.get(agentId, instructionId, requestOptions).body();
    }

    public void delete(String agentId, String instructionId) {
        this.rawClient.delete(agentId, instructionId).body();
    }

    public void delete(String agentId, String instructionId, RequestOptions requestOptions) {
        this.rawClient.delete(agentId, instructionId, requestOptions).body();
    }

    public Instruction update(String agentId, String instructionId) {
        return this.rawClient.update(agentId, instructionId).body();
    }

    public Instruction update(String agentId, String instructionId, RequestOptions requestOptions) {
        return this.rawClient.update(agentId, instructionId, requestOptions).body();
    }

    public Instruction update(String agentId, String instructionId, UpdateInstructionRequest request) {
        return this.rawClient.update(agentId, instructionId, request).body();
    }

    public Instruction update(
            String agentId, String instructionId, UpdateInstructionRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .update(agentId, instructionId, request, requestOptions)
                .body();
    }

    public CredentialsClient credentials() {
        return this.credentialsClient.get();
    }

    public VerifyClient verify() {
        return this.verifyClient.get();
    }
}
