/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.agentic.enrollments;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.agentic.enrollments.requests.CreateEnrollmentRequest;
import com.basistheory.resources.agentic.enrollments.requests.EnrollmentsListRequest;
import com.basistheory.resources.agentic.enrollments.verify.AsyncVerifyClient;
import com.basistheory.types.Enrollment;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncEnrollmentsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEnrollmentsClient rawClient;

    protected final Supplier<AsyncVerifyClient> verifyClient;

    public AsyncEnrollmentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEnrollmentsClient(clientOptions);
        this.verifyClient = Suppliers.memoize(() -> new AsyncVerifyClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEnrollmentsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List all enrollments for the current tenant with cursor-based pagination.
     */
    public CompletableFuture<SyncPagingIterable<Enrollment>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * List all enrollments for the current tenant with cursor-based pagination.
     */
    public CompletableFuture<SyncPagingIterable<Enrollment>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * List all enrollments for the current tenant with cursor-based pagination.
     */
    public CompletableFuture<SyncPagingIterable<Enrollment>> list(EnrollmentsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * List all enrollments for the current tenant with cursor-based pagination.
     */
    public CompletableFuture<SyncPagingIterable<Enrollment>> list(
            EnrollmentsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Enroll a card token with a card network (Visa or Mastercard).
     */
    public CompletableFuture<Enrollment> create(CreateEnrollmentRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Enroll a card token with a card network (Visa or Mastercard).
     */
    public CompletableFuture<Enrollment> create(CreateEnrollmentRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Enrollment> get(String enrollmentId) {
        return this.rawClient.get(enrollmentId).thenApply(response -> response.body());
    }

    public CompletableFuture<Enrollment> get(String enrollmentId, RequestOptions requestOptions) {
        return this.rawClient.get(enrollmentId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes the enrollment by marking its status as deleted.
     */
    public CompletableFuture<Void> delete(String enrollmentId) {
        return this.rawClient.delete(enrollmentId).thenApply(response -> response.body());
    }

    /**
     * Soft-deletes the enrollment by marking its status as deleted.
     */
    public CompletableFuture<Void> delete(String enrollmentId, RequestOptions requestOptions) {
        return this.rawClient.delete(enrollmentId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retry enrolling a card that previously failed. Only failed enrollments can be retried.
     */
    public CompletableFuture<Enrollment> retry(String enrollmentId) {
        return this.rawClient.retry(enrollmentId).thenApply(response -> response.body());
    }

    /**
     * Retry enrolling a card that previously failed. Only failed enrollments can be retried.
     */
    public CompletableFuture<Enrollment> retry(String enrollmentId, RequestOptions requestOptions) {
        return this.rawClient.retry(enrollmentId, requestOptions).thenApply(response -> response.body());
    }

    public AsyncVerifyClient verify() {
        return this.verifyClient.get();
    }
}
