/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.enrichments;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.enrichments.requests.BankVerificationRequest;
import com.basistheory.resources.enrichments.requests.EnrichmentsCardDetailsRequest;
import com.basistheory.types.BankVerificationResponse;
import com.basistheory.types.CardDetailsResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncEnrichmentsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawEnrichmentsClient rawClient;

    public AsyncEnrichmentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawEnrichmentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawEnrichmentsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<BankVerificationResponse> bankAccountVerify(BankVerificationRequest request) {
        return this.rawClient.bankAccountVerify(request).thenApply(response -> response.body());
    }

    public CompletableFuture<BankVerificationResponse> bankAccountVerify(
            BankVerificationRequest request, RequestOptions requestOptions) {
        return this.rawClient.bankAccountVerify(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<CardDetailsResponse> cardDetails(EnrichmentsCardDetailsRequest request) {
        return this.rawClient.cardDetails(request).thenApply(response -> response.body());
    }

    public CompletableFuture<CardDetailsResponse> cardDetails(
            EnrichmentsCardDetailsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cardDetails(request, requestOptions).thenApply(response -> response.body());
    }
}
