/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.enrichments;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.enrichments.requests.BankVerificationRequest;
import com.basistheory.resources.enrichments.requests.EnrichmentsCardDetailsRequest;
import com.basistheory.types.BankVerificationResponse;
import com.basistheory.types.CardDetailsResponse;

public class EnrichmentsClient {
    protected final ClientOptions clientOptions;

    private final RawEnrichmentsClient rawClient;

    public EnrichmentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEnrichmentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEnrichmentsClient withRawResponse() {
        return this.rawClient;
    }

    public BankVerificationResponse bankAccountVerify(BankVerificationRequest request) {
        return this.rawClient.bankAccountVerify(request).body();
    }

    public BankVerificationResponse bankAccountVerify(BankVerificationRequest request, RequestOptions requestOptions) {
        return this.rawClient.bankAccountVerify(request, requestOptions).body();
    }

    public CardDetailsResponse cardDetails(EnrichmentsCardDetailsRequest request) {
        return this.rawClient.cardDetails(request).body();
    }

    public CardDetailsResponse cardDetails(EnrichmentsCardDetailsRequest request, RequestOptions requestOptions) {
        return this.rawClient.cardDetails(request, requestOptions).body();
    }
}
