/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.permissions.requests;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PermissionsListRequest.Builder.class)
public final class PermissionsListRequest {
    private final Optional<String> applicationType;

    private final Map<String, Object> additionalProperties;

    private PermissionsListRequest(Optional<String> applicationType, Map<String, Object> additionalProperties) {
        this.applicationType = applicationType;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("application_type")
    public Optional<String> getApplicationType() {
        return applicationType;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PermissionsListRequest && equalTo((PermissionsListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PermissionsListRequest other) {
        return applicationType.equals(other.applicationType);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.applicationType);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> applicationType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PermissionsListRequest other) {
            applicationType(other.getApplicationType());
            return this;
        }

        @JsonSetter(value = "application_type", nulls = Nulls.SKIP)
        public Builder applicationType(Optional<String> applicationType) {
            this.applicationType = applicationType;
            return this;
        }

        public Builder applicationType(String applicationType) {
            this.applicationType = Optional.ofNullable(applicationType);
            return this;
        }

        public PermissionsListRequest build() {
            return new PermissionsListRequest(applicationType, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
