/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.applicationkeys;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.IdempotentRequestOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.applicationkeys.requests.ApplicationKeysListRequest;
import com.basistheory.types.ApplicationKey;
import java.util.List;

public class ApplicationKeysClient {
    protected final ClientOptions clientOptions;

    private final RawApplicationKeysClient rawClient;

    public ApplicationKeysClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawApplicationKeysClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawApplicationKeysClient withRawResponse() {
        return this.rawClient;
    }

    public List<ApplicationKey> list(String id) {
        return this.rawClient.list(id).body();
    }

    public List<ApplicationKey> list(String id, RequestOptions requestOptions) {
        return this.rawClient.list(id, requestOptions).body();
    }

    public List<ApplicationKey> list(String id, ApplicationKeysListRequest request) {
        return this.rawClient.list(id, request).body();
    }

    public List<ApplicationKey> list(String id, ApplicationKeysListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(id, request, requestOptions).body();
    }

    public ApplicationKey create(String id) {
        return this.rawClient.create(id).body();
    }

    public ApplicationKey create(String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.create(id, requestOptions).body();
    }

    public ApplicationKey get(String id, String keyId) {
        return this.rawClient.get(id, keyId).body();
    }

    public ApplicationKey get(String id, String keyId, RequestOptions requestOptions) {
        return this.rawClient.get(id, keyId, requestOptions).body();
    }

    public void delete(String id, String keyId) {
        this.rawClient.delete(id, keyId).body();
    }

    public void delete(String id, String keyId, RequestOptions requestOptions) {
        this.rawClient.delete(id, keyId, requestOptions).body();
    }
}
