/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.permissions;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.permissions.requests.PermissionsListRequest;
import com.basistheory.types.Permission;
import java.util.List;

public class PermissionsClient {
    protected final ClientOptions clientOptions;

    private final RawPermissionsClient rawClient;

    public PermissionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPermissionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPermissionsClient withRawResponse() {
        return this.rawClient;
    }

    public List<Permission> list() {
        return this.rawClient.list().body();
    }

    public List<Permission> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    public List<Permission> list(PermissionsListRequest request) {
        return this.rawClient.list(request).body();
    }

    public List<Permission> list(PermissionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }
}
