/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.reactors;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.IdempotentRequestOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.core.pagination.SyncPagingIterable;
import com.basistheory.resources.reactors.requests.CreateReactorRequest;
import com.basistheory.resources.reactors.requests.PatchReactorRequest;
import com.basistheory.resources.reactors.requests.ReactorsListRequest;
import com.basistheory.resources.reactors.requests.UpdateReactorRequest;
import com.basistheory.resources.reactors.results.AsyncResultsClient;
import com.basistheory.types.AsyncReactResponse;
import com.basistheory.types.ReactResponse;
import com.basistheory.types.Reactor;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncReactorsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawReactorsClient rawClient;

    protected final Supplier<AsyncResultsClient> resultsClient;

    public AsyncReactorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawReactorsClient(clientOptions);
        this.resultsClient = Suppliers.memoize(() -> new AsyncResultsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawReactorsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<SyncPagingIterable<Reactor>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    public CompletableFuture<SyncPagingIterable<Reactor>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<SyncPagingIterable<Reactor>> list(ReactorsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    public CompletableFuture<SyncPagingIterable<Reactor>> list(
            ReactorsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> create(CreateReactorRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> create(CreateReactorRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> update(String id, UpdateReactorRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Reactor> update(
            String id, UpdateReactorRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> patch(String id) {
        return this.rawClient.patch(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> patch(String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.patch(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> patch(String id, PatchReactorRequest request) {
        return this.rawClient.patch(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> patch(
            String id, PatchReactorRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.patch(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<ReactResponse> react(String id, Object request) {
        return this.rawClient.react(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<ReactResponse> react(String id, Object request, RequestOptions requestOptions) {
        return this.rawClient.react(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<AsyncReactResponse> reactAsync(String id, Object request) {
        return this.rawClient.reactAsync(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<AsyncReactResponse> reactAsync(String id, Object request, RequestOptions requestOptions) {
        return this.rawClient.reactAsync(id, request, requestOptions).thenApply(response -> response.body());
    }

    public AsyncResultsClient results() {
        return this.resultsClient.get();
    }
}
