/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.tenants.connections;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.IdempotentRequestOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.tenants.connections.requests.CreateTenantConnectionRequest;
import com.basistheory.types.CreateTenantConnectionResponse;

public class ConnectionsClient {
    protected final ClientOptions clientOptions;

    private final RawConnectionsClient rawClient;

    public ConnectionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawConnectionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawConnectionsClient withRawResponse() {
        return this.rawClient;
    }

    public CreateTenantConnectionResponse create(CreateTenantConnectionRequest request) {
        return this.rawClient.create(request).body();
    }

    public CreateTenantConnectionResponse create(
            CreateTenantConnectionRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public void delete() {
        this.rawClient.delete().body();
    }

    public void delete(RequestOptions requestOptions) {
        this.rawClient.delete(requestOptions).body();
    }
}
