/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.applepay.merchant;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.core.Suppliers;
import com.basistheory.resources.applepay.merchant.certificates.CertificatesClient;
import com.basistheory.resources.applepay.merchant.requests.ApplePayMerchantRegisterRequest;
import com.basistheory.types.ApplePayMerchant;
import java.util.function.Supplier;

public class MerchantClient {
    protected final ClientOptions clientOptions;

    private final RawMerchantClient rawClient;

    protected final Supplier<CertificatesClient> certificatesClient;

    public MerchantClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMerchantClient(clientOptions);
        this.certificatesClient = Suppliers.memoize(() -> new CertificatesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMerchantClient withRawResponse() {
        return this.rawClient;
    }

    public ApplePayMerchant get(String id) {
        return this.rawClient.get(id).body();
    }

    public ApplePayMerchant get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    public void delete(String id) {
        this.rawClient.delete(id).body();
    }

    public void delete(String id, RequestOptions requestOptions) {
        this.rawClient.delete(id, requestOptions).body();
    }

    public ApplePayMerchant create() {
        return this.rawClient.create().body();
    }

    public ApplePayMerchant create(RequestOptions requestOptions) {
        return this.rawClient.create(requestOptions).body();
    }

    public ApplePayMerchant create(ApplePayMerchantRegisterRequest request) {
        return this.rawClient.create(request).body();
    }

    public ApplePayMerchant create(ApplePayMerchantRegisterRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    public CertificatesClient certificates() {
        return this.certificatesClient.get();
    }
}
