/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ApplePayMerchantCertificates.Builder.class)
public final class ApplePayMerchantCertificates {
    private final Optional<String> id;

    private final Optional<String> tenantId;

    private final Optional<String> domain;

    private final Optional<OffsetDateTime> merchantCertificateExpirationDate;

    private final Optional<String> merchantCertificateFingerprint;

    private final Optional<OffsetDateTime> paymentProcessorCertificateExpirationDate;

    private final Optional<String> paymentProcessorCertificateFingerprint;

    private final Optional<String> createdBy;

    private final Optional<OffsetDateTime> createdAt;

    private final Map<String, Object> additionalProperties;

    private ApplePayMerchantCertificates(
            Optional<String> id,
            Optional<String> tenantId,
            Optional<String> domain,
            Optional<OffsetDateTime> merchantCertificateExpirationDate,
            Optional<String> merchantCertificateFingerprint,
            Optional<OffsetDateTime> paymentProcessorCertificateExpirationDate,
            Optional<String> paymentProcessorCertificateFingerprint,
            Optional<String> createdBy,
            Optional<OffsetDateTime> createdAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.tenantId = tenantId;
        this.domain = domain;
        this.merchantCertificateExpirationDate = merchantCertificateExpirationDate;
        this.merchantCertificateFingerprint = merchantCertificateFingerprint;
        this.paymentProcessorCertificateExpirationDate = paymentProcessorCertificateExpirationDate;
        this.paymentProcessorCertificateFingerprint = paymentProcessorCertificateFingerprint;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("tenant_id")
    public Optional<String> getTenantId() {
        return tenantId;
    }

    @JsonProperty("domain")
    public Optional<String> getDomain() {
        return domain;
    }

    @JsonProperty("merchant_certificate_expiration_date")
    public Optional<OffsetDateTime> getMerchantCertificateExpirationDate() {
        return merchantCertificateExpirationDate;
    }

    @JsonProperty("merchant_certificate_fingerprint")
    public Optional<String> getMerchantCertificateFingerprint() {
        return merchantCertificateFingerprint;
    }

    @JsonProperty("payment_processor_certificate_expiration_date")
    public Optional<OffsetDateTime> getPaymentProcessorCertificateExpirationDate() {
        return paymentProcessorCertificateExpirationDate;
    }

    @JsonProperty("payment_processor_certificate_fingerprint")
    public Optional<String> getPaymentProcessorCertificateFingerprint() {
        return paymentProcessorCertificateFingerprint;
    }

    @JsonProperty("created_by")
    public Optional<String> getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ApplePayMerchantCertificates && equalTo((ApplePayMerchantCertificates) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ApplePayMerchantCertificates other) {
        return id.equals(other.id)
                && tenantId.equals(other.tenantId)
                && domain.equals(other.domain)
                && merchantCertificateExpirationDate.equals(other.merchantCertificateExpirationDate)
                && merchantCertificateFingerprint.equals(other.merchantCertificateFingerprint)
                && paymentProcessorCertificateExpirationDate.equals(other.paymentProcessorCertificateExpirationDate)
                && paymentProcessorCertificateFingerprint.equals(other.paymentProcessorCertificateFingerprint)
                && createdBy.equals(other.createdBy)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.tenantId,
                this.domain,
                this.merchantCertificateExpirationDate,
                this.merchantCertificateFingerprint,
                this.paymentProcessorCertificateExpirationDate,
                this.paymentProcessorCertificateFingerprint,
                this.createdBy,
                this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> tenantId = Optional.empty();

        private Optional<String> domain = Optional.empty();

        private Optional<OffsetDateTime> merchantCertificateExpirationDate = Optional.empty();

        private Optional<String> merchantCertificateFingerprint = Optional.empty();

        private Optional<OffsetDateTime> paymentProcessorCertificateExpirationDate = Optional.empty();

        private Optional<String> paymentProcessorCertificateFingerprint = Optional.empty();

        private Optional<String> createdBy = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ApplePayMerchantCertificates other) {
            id(other.getId());
            tenantId(other.getTenantId());
            domain(other.getDomain());
            merchantCertificateExpirationDate(other.getMerchantCertificateExpirationDate());
            merchantCertificateFingerprint(other.getMerchantCertificateFingerprint());
            paymentProcessorCertificateExpirationDate(other.getPaymentProcessorCertificateExpirationDate());
            paymentProcessorCertificateFingerprint(other.getPaymentProcessorCertificateFingerprint());
            createdBy(other.getCreatedBy());
            createdAt(other.getCreatedAt());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "tenant_id", nulls = Nulls.SKIP)
        public Builder tenantId(Optional<String> tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        public Builder tenantId(String tenantId) {
            this.tenantId = Optional.ofNullable(tenantId);
            return this;
        }

        @JsonSetter(value = "domain", nulls = Nulls.SKIP)
        public Builder domain(Optional<String> domain) {
            this.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            this.domain = Optional.ofNullable(domain);
            return this;
        }

        @JsonSetter(value = "merchant_certificate_expiration_date", nulls = Nulls.SKIP)
        public Builder merchantCertificateExpirationDate(Optional<OffsetDateTime> merchantCertificateExpirationDate) {
            this.merchantCertificateExpirationDate = merchantCertificateExpirationDate;
            return this;
        }

        public Builder merchantCertificateExpirationDate(OffsetDateTime merchantCertificateExpirationDate) {
            this.merchantCertificateExpirationDate = Optional.ofNullable(merchantCertificateExpirationDate);
            return this;
        }

        @JsonSetter(value = "merchant_certificate_fingerprint", nulls = Nulls.SKIP)
        public Builder merchantCertificateFingerprint(Optional<String> merchantCertificateFingerprint) {
            this.merchantCertificateFingerprint = merchantCertificateFingerprint;
            return this;
        }

        public Builder merchantCertificateFingerprint(String merchantCertificateFingerprint) {
            this.merchantCertificateFingerprint = Optional.ofNullable(merchantCertificateFingerprint);
            return this;
        }

        @JsonSetter(value = "payment_processor_certificate_expiration_date", nulls = Nulls.SKIP)
        public Builder paymentProcessorCertificateExpirationDate(
                Optional<OffsetDateTime> paymentProcessorCertificateExpirationDate) {
            this.paymentProcessorCertificateExpirationDate = paymentProcessorCertificateExpirationDate;
            return this;
        }

        public Builder paymentProcessorCertificateExpirationDate(
                OffsetDateTime paymentProcessorCertificateExpirationDate) {
            this.paymentProcessorCertificateExpirationDate =
                    Optional.ofNullable(paymentProcessorCertificateExpirationDate);
            return this;
        }

        @JsonSetter(value = "payment_processor_certificate_fingerprint", nulls = Nulls.SKIP)
        public Builder paymentProcessorCertificateFingerprint(Optional<String> paymentProcessorCertificateFingerprint) {
            this.paymentProcessorCertificateFingerprint = paymentProcessorCertificateFingerprint;
            return this;
        }

        public Builder paymentProcessorCertificateFingerprint(String paymentProcessorCertificateFingerprint) {
            this.paymentProcessorCertificateFingerprint = Optional.ofNullable(paymentProcessorCertificateFingerprint);
            return this;
        }

        @JsonSetter(value = "created_by", nulls = Nulls.SKIP)
        public Builder createdBy(Optional<String> createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        public Builder createdBy(String createdBy) {
            this.createdBy = Optional.ofNullable(createdBy);
            return this;
        }

        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        public ApplePayMerchantCertificates build() {
            return new ApplePayMerchantCertificates(
                    id,
                    tenantId,
                    domain,
                    merchantCertificateExpirationDate,
                    merchantCertificateFingerprint,
                    paymentProcessorCertificateExpirationDate,
                    paymentProcessorCertificateFingerprint,
                    createdBy,
                    createdAt,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
