/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateTenantConnectionResponse.Builder.class)
public final class CreateTenantConnectionResponse {
    private final Optional<String> connectionId;

    private final Map<String, Object> additionalProperties;

    private CreateTenantConnectionResponse(Optional<String> connectionId, Map<String, Object> additionalProperties) {
        this.connectionId = connectionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connection_id")
    public Optional<String> getConnectionId() {
        return connectionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateTenantConnectionResponse && equalTo((CreateTenantConnectionResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateTenantConnectionResponse other) {
        return connectionId.equals(other.connectionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.connectionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> connectionId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateTenantConnectionResponse other) {
            connectionId(other.getConnectionId());
            return this;
        }

        @JsonSetter(value = "connection_id", nulls = Nulls.SKIP)
        public Builder connectionId(Optional<String> connectionId) {
            this.connectionId = connectionId;
            return this;
        }

        public Builder connectionId(String connectionId) {
            this.connectionId = Optional.ofNullable(connectionId);
            return this;
        }

        public CreateTenantConnectionResponse build() {
            return new CreateTenantConnectionResponse(connectionId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
