/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Credentials.Builder.class)
public final class Credentials {
    private final Optional<CredentialsCard> card;

    private final Optional<CredentialsSpt> spt;

    private final Optional<CredentialsMpp> mpp;

    private final Optional<OffsetDateTime> expiresAt;

    private final Map<String, Object> additionalProperties;

    private Credentials(
            Optional<CredentialsCard> card,
            Optional<CredentialsSpt> spt,
            Optional<CredentialsMpp> mpp,
            Optional<OffsetDateTime> expiresAt,
            Map<String, Object> additionalProperties) {
        this.card = card;
        this.spt = spt;
        this.mpp = mpp;
        this.expiresAt = expiresAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("card")
    public Optional<CredentialsCard> getCard() {
        return card;
    }

    /**
     * @return Stripe shared payment token (raw mode)
     */
    @JsonProperty("spt")
    public Optional<CredentialsSpt> getSpt() {
        return spt;
    }

    /**
     * @return MPP credential (MPP mode)
     */
    @JsonProperty("mpp")
    public Optional<CredentialsMpp> getMpp() {
        return mpp;
    }

    @JsonProperty("expires_at")
    public Optional<OffsetDateTime> getExpiresAt() {
        return expiresAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Credentials && equalTo((Credentials) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Credentials other) {
        return card.equals(other.card)
                && spt.equals(other.spt)
                && mpp.equals(other.mpp)
                && expiresAt.equals(other.expiresAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.card, this.spt, this.mpp, this.expiresAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CredentialsCard> card = Optional.empty();

        private Optional<CredentialsSpt> spt = Optional.empty();

        private Optional<CredentialsMpp> mpp = Optional.empty();

        private Optional<OffsetDateTime> expiresAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Credentials other) {
            card(other.getCard());
            spt(other.getSpt());
            mpp(other.getMpp());
            expiresAt(other.getExpiresAt());
            return this;
        }

        @JsonSetter(value = "card", nulls = Nulls.SKIP)
        public Builder card(Optional<CredentialsCard> card) {
            this.card = card;
            return this;
        }

        public Builder card(CredentialsCard card) {
            this.card = Optional.ofNullable(card);
            return this;
        }

        /**
         * <p>Stripe shared payment token (raw mode)</p>
         */
        @JsonSetter(value = "spt", nulls = Nulls.SKIP)
        public Builder spt(Optional<CredentialsSpt> spt) {
            this.spt = spt;
            return this;
        }

        public Builder spt(CredentialsSpt spt) {
            this.spt = Optional.ofNullable(spt);
            return this;
        }

        /**
         * <p>MPP credential (MPP mode)</p>
         */
        @JsonSetter(value = "mpp", nulls = Nulls.SKIP)
        public Builder mpp(Optional<CredentialsMpp> mpp) {
            this.mpp = mpp;
            return this;
        }

        public Builder mpp(CredentialsMpp mpp) {
            this.mpp = Optional.ofNullable(mpp);
            return this;
        }

        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public Builder expiresAt(Optional<OffsetDateTime> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public Builder expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        public Credentials build() {
            return new Credentials(card, spt, mpp, expiresAt, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
