/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeviceContext.Builder.class)
public final class DeviceContext {
    private final int screenHeight;

    private final int screenWidth;

    private final String userAgentString;

    private final String languageCode;

    private final String timeZone;

    private final boolean javaScriptEnabled;

    private final String clientDeviceId;

    private final String clientReferenceId;

    private final DeviceContextPlatformType platformType;

    private final Optional<Integer> colorDepth;

    private final Optional<String> acceptHeader;

    private final Optional<String> ipAddress;

    private final Optional<DeviceContextSessionContext> sessionContext;

    private final Map<String, Object> additionalProperties;

    private DeviceContext(
            int screenHeight,
            int screenWidth,
            String userAgentString,
            String languageCode,
            String timeZone,
            boolean javaScriptEnabled,
            String clientDeviceId,
            String clientReferenceId,
            DeviceContextPlatformType platformType,
            Optional<Integer> colorDepth,
            Optional<String> acceptHeader,
            Optional<String> ipAddress,
            Optional<DeviceContextSessionContext> sessionContext,
            Map<String, Object> additionalProperties) {
        this.screenHeight = screenHeight;
        this.screenWidth = screenWidth;
        this.userAgentString = userAgentString;
        this.languageCode = languageCode;
        this.timeZone = timeZone;
        this.javaScriptEnabled = javaScriptEnabled;
        this.clientDeviceId = clientDeviceId;
        this.clientReferenceId = clientReferenceId;
        this.platformType = platformType;
        this.colorDepth = colorDepth;
        this.acceptHeader = acceptHeader;
        this.ipAddress = ipAddress;
        this.sessionContext = sessionContext;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("screen_height")
    public int getScreenHeight() {
        return screenHeight;
    }

    @JsonProperty("screen_width")
    public int getScreenWidth() {
        return screenWidth;
    }

    @JsonProperty("user_agent_string")
    public String getUserAgentString() {
        return userAgentString;
    }

    @JsonProperty("language_code")
    public String getLanguageCode() {
        return languageCode;
    }

    @JsonProperty("time_zone")
    public String getTimeZone() {
        return timeZone;
    }

    @JsonProperty("java_script_enabled")
    public boolean getJavaScriptEnabled() {
        return javaScriptEnabled;
    }

    @JsonProperty("client_device_id")
    public String getClientDeviceId() {
        return clientDeviceId;
    }

    @JsonProperty("client_reference_id")
    public String getClientReferenceId() {
        return clientReferenceId;
    }

    @JsonProperty("platform_type")
    public DeviceContextPlatformType getPlatformType() {
        return platformType;
    }

    @JsonProperty("color_depth")
    public Optional<Integer> getColorDepth() {
        return colorDepth;
    }

    @JsonProperty("accept_header")
    public Optional<String> getAcceptHeader() {
        return acceptHeader;
    }

    /**
     * @return Auto-filled from request IP if not provided
     */
    @JsonProperty("ip_address")
    public Optional<String> getIpAddress() {
        return ipAddress;
    }

    @JsonProperty("session_context")
    public Optional<DeviceContextSessionContext> getSessionContext() {
        return sessionContext;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeviceContext && equalTo((DeviceContext) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeviceContext other) {
        return screenHeight == other.screenHeight
                && screenWidth == other.screenWidth
                && userAgentString.equals(other.userAgentString)
                && languageCode.equals(other.languageCode)
                && timeZone.equals(other.timeZone)
                && javaScriptEnabled == other.javaScriptEnabled
                && clientDeviceId.equals(other.clientDeviceId)
                && clientReferenceId.equals(other.clientReferenceId)
                && platformType.equals(other.platformType)
                && colorDepth.equals(other.colorDepth)
                && acceptHeader.equals(other.acceptHeader)
                && ipAddress.equals(other.ipAddress)
                && sessionContext.equals(other.sessionContext);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.screenHeight,
                this.screenWidth,
                this.userAgentString,
                this.languageCode,
                this.timeZone,
                this.javaScriptEnabled,
                this.clientDeviceId,
                this.clientReferenceId,
                this.platformType,
                this.colorDepth,
                this.acceptHeader,
                this.ipAddress,
                this.sessionContext);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ScreenHeightStage builder() {
        return new Builder();
    }

    public interface ScreenHeightStage {
        ScreenWidthStage screenHeight(int screenHeight);

        Builder from(DeviceContext other);
    }

    public interface ScreenWidthStage {
        UserAgentStringStage screenWidth(int screenWidth);
    }

    public interface UserAgentStringStage {
        LanguageCodeStage userAgentString(@NotNull String userAgentString);
    }

    public interface LanguageCodeStage {
        TimeZoneStage languageCode(@NotNull String languageCode);
    }

    public interface TimeZoneStage {
        JavaScriptEnabledStage timeZone(@NotNull String timeZone);
    }

    public interface JavaScriptEnabledStage {
        ClientDeviceIdStage javaScriptEnabled(boolean javaScriptEnabled);
    }

    public interface ClientDeviceIdStage {
        ClientReferenceIdStage clientDeviceId(@NotNull String clientDeviceId);
    }

    public interface ClientReferenceIdStage {
        PlatformTypeStage clientReferenceId(@NotNull String clientReferenceId);
    }

    public interface PlatformTypeStage {
        _FinalStage platformType(@NotNull DeviceContextPlatformType platformType);
    }

    public interface _FinalStage {
        DeviceContext build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage colorDepth(Optional<Integer> colorDepth);

        _FinalStage colorDepth(Integer colorDepth);

        _FinalStage acceptHeader(Optional<String> acceptHeader);

        _FinalStage acceptHeader(String acceptHeader);

        /**
         * <p>Auto-filled from request IP if not provided</p>
         */
        _FinalStage ipAddress(Optional<String> ipAddress);

        _FinalStage ipAddress(String ipAddress);

        _FinalStage sessionContext(Optional<DeviceContextSessionContext> sessionContext);

        _FinalStage sessionContext(DeviceContextSessionContext sessionContext);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ScreenHeightStage,
                    ScreenWidthStage,
                    UserAgentStringStage,
                    LanguageCodeStage,
                    TimeZoneStage,
                    JavaScriptEnabledStage,
                    ClientDeviceIdStage,
                    ClientReferenceIdStage,
                    PlatformTypeStage,
                    _FinalStage {
        private int screenHeight;

        private int screenWidth;

        private String userAgentString;

        private String languageCode;

        private String timeZone;

        private boolean javaScriptEnabled;

        private String clientDeviceId;

        private String clientReferenceId;

        private DeviceContextPlatformType platformType;

        private Optional<DeviceContextSessionContext> sessionContext = Optional.empty();

        private Optional<String> ipAddress = Optional.empty();

        private Optional<String> acceptHeader = Optional.empty();

        private Optional<Integer> colorDepth = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeviceContext other) {
            screenHeight(other.getScreenHeight());
            screenWidth(other.getScreenWidth());
            userAgentString(other.getUserAgentString());
            languageCode(other.getLanguageCode());
            timeZone(other.getTimeZone());
            javaScriptEnabled(other.getJavaScriptEnabled());
            clientDeviceId(other.getClientDeviceId());
            clientReferenceId(other.getClientReferenceId());
            platformType(other.getPlatformType());
            colorDepth(other.getColorDepth());
            acceptHeader(other.getAcceptHeader());
            ipAddress(other.getIpAddress());
            sessionContext(other.getSessionContext());
            return this;
        }

        @java.lang.Override
        @JsonSetter("screen_height")
        public ScreenWidthStage screenHeight(int screenHeight) {
            this.screenHeight = screenHeight;
            return this;
        }

        @java.lang.Override
        @JsonSetter("screen_width")
        public UserAgentStringStage screenWidth(int screenWidth) {
            this.screenWidth = screenWidth;
            return this;
        }

        @java.lang.Override
        @JsonSetter("user_agent_string")
        public LanguageCodeStage userAgentString(@NotNull String userAgentString) {
            this.userAgentString = Objects.requireNonNull(userAgentString, "userAgentString must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("language_code")
        public TimeZoneStage languageCode(@NotNull String languageCode) {
            this.languageCode = Objects.requireNonNull(languageCode, "languageCode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("time_zone")
        public JavaScriptEnabledStage timeZone(@NotNull String timeZone) {
            this.timeZone = Objects.requireNonNull(timeZone, "timeZone must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("java_script_enabled")
        public ClientDeviceIdStage javaScriptEnabled(boolean javaScriptEnabled) {
            this.javaScriptEnabled = javaScriptEnabled;
            return this;
        }

        @java.lang.Override
        @JsonSetter("client_device_id")
        public ClientReferenceIdStage clientDeviceId(@NotNull String clientDeviceId) {
            this.clientDeviceId = Objects.requireNonNull(clientDeviceId, "clientDeviceId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("client_reference_id")
        public PlatformTypeStage clientReferenceId(@NotNull String clientReferenceId) {
            this.clientReferenceId = Objects.requireNonNull(clientReferenceId, "clientReferenceId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("platform_type")
        public _FinalStage platformType(@NotNull DeviceContextPlatformType platformType) {
            this.platformType = Objects.requireNonNull(platformType, "platformType must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage sessionContext(DeviceContextSessionContext sessionContext) {
            this.sessionContext = Optional.ofNullable(sessionContext);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "session_context", nulls = Nulls.SKIP)
        public _FinalStage sessionContext(Optional<DeviceContextSessionContext> sessionContext) {
            this.sessionContext = sessionContext;
            return this;
        }

        /**
         * <p>Auto-filled from request IP if not provided</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ipAddress(String ipAddress) {
            this.ipAddress = Optional.ofNullable(ipAddress);
            return this;
        }

        /**
         * <p>Auto-filled from request IP if not provided</p>
         */
        @java.lang.Override
        @JsonSetter(value = "ip_address", nulls = Nulls.SKIP)
        public _FinalStage ipAddress(Optional<String> ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }

        @java.lang.Override
        public _FinalStage acceptHeader(String acceptHeader) {
            this.acceptHeader = Optional.ofNullable(acceptHeader);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "accept_header", nulls = Nulls.SKIP)
        public _FinalStage acceptHeader(Optional<String> acceptHeader) {
            this.acceptHeader = acceptHeader;
            return this;
        }

        @java.lang.Override
        public _FinalStage colorDepth(Integer colorDepth) {
            this.colorDepth = Optional.ofNullable(colorDepth);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "color_depth", nulls = Nulls.SKIP)
        public _FinalStage colorDepth(Optional<Integer> colorDepth) {
            this.colorDepth = colorDepth;
            return this;
        }

        @java.lang.Override
        public DeviceContext build() {
            return new DeviceContext(
                    screenHeight,
                    screenWidth,
                    userAgentString,
                    languageCode,
                    timeZone,
                    javaScriptEnabled,
                    clientDeviceId,
                    clientReferenceId,
                    platformType,
                    colorDepth,
                    acceptHeader,
                    ipAddress,
                    sessionContext,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
