/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DiscoverConfig.Builder.class)
public final class DiscoverConfig {
    private final Optional<String> merchantIdMid;

    private final Map<String, Object> additionalProperties;

    private DiscoverConfig(Optional<String> merchantIdMid, Map<String, Object> additionalProperties) {
        this.merchantIdMid = merchantIdMid;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("merchant_id_mid")
    public Optional<String> getMerchantIdMid() {
        return merchantIdMid;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DiscoverConfig && equalTo((DiscoverConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DiscoverConfig other) {
        return merchantIdMid.equals(other.merchantIdMid);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.merchantIdMid);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> merchantIdMid = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DiscoverConfig other) {
            merchantIdMid(other.getMerchantIdMid());
            return this;
        }

        @JsonSetter(value = "merchant_id_mid", nulls = Nulls.SKIP)
        public Builder merchantIdMid(Optional<String> merchantIdMid) {
            this.merchantIdMid = merchantIdMid;
            return this;
        }

        public Builder merchantIdMid(String merchantIdMid) {
            this.merchantIdMid = Optional.ofNullable(merchantIdMid);
            return this;
        }

        public DiscoverConfig build() {
            return new DiscoverConfig(merchantIdMid, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
