/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EnrollmentType {
    AGENTIC("agentic"),

    AUTOFILL("autofill"),

    SPT("spt");

    private final String value;

    EnrollmentType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
