/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum InstructionCredentialType {
    CARD("card"),

    SPT("spt"),

    MPP("mpp");

    private final String value;

    InstructionCredentialType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
