/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MppChallenge.Builder.class)
public final class MppChallenge {
    private final String id;

    private final String realm;

    private final String amount;

    private final String currency;

    private final List<String> acceptedNetworks;

    private final String merchantName;

    private final Optional<EncryptionJwk> encryptionJwk;

    private final Optional<String> jwksUri;

    private final Optional<String> kid;

    private final Map<String, Object> additionalProperties;

    private MppChallenge(
            String id,
            String realm,
            String amount,
            String currency,
            List<String> acceptedNetworks,
            String merchantName,
            Optional<EncryptionJwk> encryptionJwk,
            Optional<String> jwksUri,
            Optional<String> kid,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.realm = realm;
        this.amount = amount;
        this.currency = currency;
        this.acceptedNetworks = acceptedNetworks;
        this.merchantName = merchantName;
        this.encryptionJwk = encryptionJwk;
        this.jwksUri = jwksUri;
        this.kid = kid;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("realm")
    public String getRealm() {
        return realm;
    }

    @JsonProperty("amount")
    public String getAmount() {
        return amount;
    }

    @JsonProperty("currency")
    public String getCurrency() {
        return currency;
    }

    @JsonProperty("accepted_networks")
    public List<String> getAcceptedNetworks() {
        return acceptedNetworks;
    }

    @JsonProperty("merchant_name")
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * @return Mutually exclusive with jwks_uri
     */
    @JsonProperty("encryption_jwk")
    public Optional<EncryptionJwk> getEncryptionJwk() {
        return encryptionJwk;
    }

    /**
     * @return Mutually exclusive with encryption_jwk
     */
    @JsonProperty("jwks_uri")
    public Optional<String> getJwksUri() {
        return jwksUri;
    }

    /**
     * @return Required when jwks_uri is provided
     */
    @JsonProperty("kid")
    public Optional<String> getKid() {
        return kid;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MppChallenge && equalTo((MppChallenge) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MppChallenge other) {
        return id.equals(other.id)
                && realm.equals(other.realm)
                && amount.equals(other.amount)
                && currency.equals(other.currency)
                && acceptedNetworks.equals(other.acceptedNetworks)
                && merchantName.equals(other.merchantName)
                && encryptionJwk.equals(other.encryptionJwk)
                && jwksUri.equals(other.jwksUri)
                && kid.equals(other.kid);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.realm,
                this.amount,
                this.currency,
                this.acceptedNetworks,
                this.merchantName,
                this.encryptionJwk,
                this.jwksUri,
                this.kid);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        RealmStage id(@NotNull String id);

        Builder from(MppChallenge other);
    }

    public interface RealmStage {
        AmountStage realm(@NotNull String realm);
    }

    public interface AmountStage {
        CurrencyStage amount(@NotNull String amount);
    }

    public interface CurrencyStage {
        MerchantNameStage currency(@NotNull String currency);
    }

    public interface MerchantNameStage {
        _FinalStage merchantName(@NotNull String merchantName);
    }

    public interface _FinalStage {
        MppChallenge build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage acceptedNetworks(List<String> acceptedNetworks);

        _FinalStage addAcceptedNetworks(String acceptedNetworks);

        _FinalStage addAllAcceptedNetworks(List<String> acceptedNetworks);

        /**
         * <p>Mutually exclusive with jwks_uri</p>
         */
        _FinalStage encryptionJwk(Optional<EncryptionJwk> encryptionJwk);

        _FinalStage encryptionJwk(EncryptionJwk encryptionJwk);

        /**
         * <p>Mutually exclusive with encryption_jwk</p>
         */
        _FinalStage jwksUri(Optional<String> jwksUri);

        _FinalStage jwksUri(String jwksUri);

        /**
         * <p>Required when jwks_uri is provided</p>
         */
        _FinalStage kid(Optional<String> kid);

        _FinalStage kid(String kid);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, RealmStage, AmountStage, CurrencyStage, MerchantNameStage, _FinalStage {
        private String id;

        private String realm;

        private String amount;

        private String currency;

        private String merchantName;

        private Optional<String> kid = Optional.empty();

        private Optional<String> jwksUri = Optional.empty();

        private Optional<EncryptionJwk> encryptionJwk = Optional.empty();

        private List<String> acceptedNetworks = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MppChallenge other) {
            id(other.getId());
            realm(other.getRealm());
            amount(other.getAmount());
            currency(other.getCurrency());
            acceptedNetworks(other.getAcceptedNetworks());
            merchantName(other.getMerchantName());
            encryptionJwk(other.getEncryptionJwk());
            jwksUri(other.getJwksUri());
            kid(other.getKid());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public RealmStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("realm")
        public AmountStage realm(@NotNull String realm) {
            this.realm = Objects.requireNonNull(realm, "realm must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("amount")
        public CurrencyStage amount(@NotNull String amount) {
            this.amount = Objects.requireNonNull(amount, "amount must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("currency")
        public MerchantNameStage currency(@NotNull String currency) {
            this.currency = Objects.requireNonNull(currency, "currency must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("merchant_name")
        public _FinalStage merchantName(@NotNull String merchantName) {
            this.merchantName = Objects.requireNonNull(merchantName, "merchantName must not be null");
            return this;
        }

        /**
         * <p>Required when jwks_uri is provided</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage kid(String kid) {
            this.kid = Optional.ofNullable(kid);
            return this;
        }

        /**
         * <p>Required when jwks_uri is provided</p>
         */
        @java.lang.Override
        @JsonSetter(value = "kid", nulls = Nulls.SKIP)
        public _FinalStage kid(Optional<String> kid) {
            this.kid = kid;
            return this;
        }

        /**
         * <p>Mutually exclusive with encryption_jwk</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage jwksUri(String jwksUri) {
            this.jwksUri = Optional.ofNullable(jwksUri);
            return this;
        }

        /**
         * <p>Mutually exclusive with encryption_jwk</p>
         */
        @java.lang.Override
        @JsonSetter(value = "jwks_uri", nulls = Nulls.SKIP)
        public _FinalStage jwksUri(Optional<String> jwksUri) {
            this.jwksUri = jwksUri;
            return this;
        }

        /**
         * <p>Mutually exclusive with jwks_uri</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage encryptionJwk(EncryptionJwk encryptionJwk) {
            this.encryptionJwk = Optional.ofNullable(encryptionJwk);
            return this;
        }

        /**
         * <p>Mutually exclusive with jwks_uri</p>
         */
        @java.lang.Override
        @JsonSetter(value = "encryption_jwk", nulls = Nulls.SKIP)
        public _FinalStage encryptionJwk(Optional<EncryptionJwk> encryptionJwk) {
            this.encryptionJwk = encryptionJwk;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllAcceptedNetworks(List<String> acceptedNetworks) {
            if (acceptedNetworks != null) {
                this.acceptedNetworks.addAll(acceptedNetworks);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addAcceptedNetworks(String acceptedNetworks) {
            this.acceptedNetworks.add(acceptedNetworks);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "accepted_networks", nulls = Nulls.SKIP)
        public _FinalStage acceptedNetworks(List<String> acceptedNetworks) {
            this.acceptedNetworks.clear();
            if (acceptedNetworks != null) {
                this.acceptedNetworks.addAll(acceptedNetworks);
            }
            return this;
        }

        @java.lang.Override
        public MppChallenge build() {
            return new MppChallenge(
                    id,
                    realm,
                    amount,
                    currency,
                    acceptedNetworks,
                    merchantName,
                    encryptionJwk,
                    jwksUri,
                    kid,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
