/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PublishConfirmationRequest.Builder.class)
public final class PublishConfirmationRequest {
    private final List<ConfirmationEntry> confirmationData;

    private final Map<String, Object> additionalProperties;

    private PublishConfirmationRequest(
            List<ConfirmationEntry> confirmationData, Map<String, Object> additionalProperties) {
        this.confirmationData = confirmationData;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("confirmation_data")
    public List<ConfirmationEntry> getConfirmationData() {
        return confirmationData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PublishConfirmationRequest && equalTo((PublishConfirmationRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PublishConfirmationRequest other) {
        return confirmationData.equals(other.confirmationData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.confirmationData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<ConfirmationEntry> confirmationData = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PublishConfirmationRequest other) {
            confirmationData(other.getConfirmationData());
            return this;
        }

        @JsonSetter(value = "confirmation_data", nulls = Nulls.SKIP)
        public Builder confirmationData(List<ConfirmationEntry> confirmationData) {
            this.confirmationData.clear();
            if (confirmationData != null) {
                this.confirmationData.addAll(confirmationData);
            }
            return this;
        }

        public Builder addConfirmationData(ConfirmationEntry confirmationData) {
            this.confirmationData.add(confirmationData);
            return this;
        }

        public Builder addAllConfirmationData(List<ConfirmationEntry> confirmationData) {
            if (confirmationData != null) {
                this.confirmationData.addAll(confirmationData);
            }
            return this;
        }

        public PublishConfirmationRequest build() {
            return new PublishConfirmationRequest(confirmationData, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
