/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SubmerchantAuthenticationResponse.Builder.class)
public final class SubmerchantAuthenticationResponse {
    private final Optional<String> merchantIdentifier;

    private final Optional<String> authenticationData;

    private final Optional<String> transactionAmount;

    private final Map<String, Object> additionalProperties;

    private SubmerchantAuthenticationResponse(
            Optional<String> merchantIdentifier,
            Optional<String> authenticationData,
            Optional<String> transactionAmount,
            Map<String, Object> additionalProperties) {
        this.merchantIdentifier = merchantIdentifier;
        this.authenticationData = authenticationData;
        this.transactionAmount = transactionAmount;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("merchant_identifier")
    public Optional<String> getMerchantIdentifier() {
        return merchantIdentifier;
    }

    @JsonProperty("authentication_data")
    public Optional<String> getAuthenticationData() {
        return authenticationData;
    }

    @JsonProperty("transaction_amount")
    public Optional<String> getTransactionAmount() {
        return transactionAmount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubmerchantAuthenticationResponse && equalTo((SubmerchantAuthenticationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubmerchantAuthenticationResponse other) {
        return merchantIdentifier.equals(other.merchantIdentifier)
                && authenticationData.equals(other.authenticationData)
                && transactionAmount.equals(other.transactionAmount);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.merchantIdentifier, this.authenticationData, this.transactionAmount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> merchantIdentifier = Optional.empty();

        private Optional<String> authenticationData = Optional.empty();

        private Optional<String> transactionAmount = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SubmerchantAuthenticationResponse other) {
            merchantIdentifier(other.getMerchantIdentifier());
            authenticationData(other.getAuthenticationData());
            transactionAmount(other.getTransactionAmount());
            return this;
        }

        @JsonSetter(value = "merchant_identifier", nulls = Nulls.SKIP)
        public Builder merchantIdentifier(Optional<String> merchantIdentifier) {
            this.merchantIdentifier = merchantIdentifier;
            return this;
        }

        public Builder merchantIdentifier(String merchantIdentifier) {
            this.merchantIdentifier = Optional.ofNullable(merchantIdentifier);
            return this;
        }

        @JsonSetter(value = "authentication_data", nulls = Nulls.SKIP)
        public Builder authenticationData(Optional<String> authenticationData) {
            this.authenticationData = authenticationData;
            return this;
        }

        public Builder authenticationData(String authenticationData) {
            this.authenticationData = Optional.ofNullable(authenticationData);
            return this;
        }

        @JsonSetter(value = "transaction_amount", nulls = Nulls.SKIP)
        public Builder transactionAmount(Optional<String> transactionAmount) {
            this.transactionAmount = transactionAmount;
            return this;
        }

        public Builder transactionAmount(String transactionAmount) {
            this.transactionAmount = Optional.ofNullable(transactionAmount);
            return this;
        }

        public SubmerchantAuthenticationResponse build() {
            return new SubmerchantAuthenticationResponse(
                    merchantIdentifier, authenticationData, transactionAmount, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
