/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TenantMerchantRequest.Builder.class)
public final class TenantMerchantRequest {
    private final String name;

    private final MerchantDetails details;

    private final Map<String, Object> additionalProperties;

    private TenantMerchantRequest(String name, MerchantDetails details, Map<String, Object> additionalProperties) {
        this.name = name;
        this.details = details;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("details")
    public MerchantDetails getDetails() {
        return details;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TenantMerchantRequest && equalTo((TenantMerchantRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TenantMerchantRequest other) {
        return name.equals(other.name) && details.equals(other.details);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.details);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        DetailsStage name(@NotNull String name);

        Builder from(TenantMerchantRequest other);
    }

    public interface DetailsStage {
        _FinalStage details(@NotNull MerchantDetails details);
    }

    public interface _FinalStage {
        TenantMerchantRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, DetailsStage, _FinalStage {
        private String name;

        private MerchantDetails details;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TenantMerchantRequest other) {
            name(other.getName());
            details(other.getDetails());
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public DetailsStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("details")
        public _FinalStage details(@NotNull MerchantDetails details) {
            this.details = Objects.requireNonNull(details, "details must not be null");
            return this;
        }

        @java.lang.Override
        public TenantMerchantRequest build() {
            return new TenantMerchantRequest(name, details, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
