/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.types;

import com.basistheory.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ThreeDsCardholderAuthenticationInfo.Builder.class)
public final class ThreeDsCardholderAuthenticationInfo {
    private final Optional<String> method;

    private final Optional<String> timestamp;

    private final Optional<String> data;

    private final Map<String, Object> additionalProperties;

    private ThreeDsCardholderAuthenticationInfo(
            Optional<String> method,
            Optional<String> timestamp,
            Optional<String> data,
            Map<String, Object> additionalProperties) {
        this.method = method;
        this.timestamp = timestamp;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("method")
    public Optional<String> getMethod() {
        return method;
    }

    @JsonProperty("timestamp")
    public Optional<String> getTimestamp() {
        return timestamp;
    }

    @JsonProperty("data")
    public Optional<String> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ThreeDsCardholderAuthenticationInfo
                && equalTo((ThreeDsCardholderAuthenticationInfo) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ThreeDsCardholderAuthenticationInfo other) {
        return method.equals(other.method) && timestamp.equals(other.timestamp) && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.method, this.timestamp, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> method = Optional.empty();

        private Optional<String> timestamp = Optional.empty();

        private Optional<String> data = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ThreeDsCardholderAuthenticationInfo other) {
            method(other.getMethod());
            timestamp(other.getTimestamp());
            data(other.getData());
            return this;
        }

        @JsonSetter(value = "method", nulls = Nulls.SKIP)
        public Builder method(Optional<String> method) {
            this.method = method;
            return this;
        }

        public Builder method(String method) {
            this.method = Optional.ofNullable(method);
            return this;
        }

        @JsonSetter(value = "timestamp", nulls = Nulls.SKIP)
        public Builder timestamp(Optional<String> timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder timestamp(String timestamp) {
            this.timestamp = Optional.ofNullable(timestamp);
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<String> data) {
            this.data = data;
            return this;
        }

        public Builder data(String data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        public ThreeDsCardholderAuthenticationInfo build() {
            return new ThreeDsCardholderAuthenticationInfo(method, timestamp, data, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
