/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.tenants.members;

import com.basistheory.core.ClientOptions;
import com.basistheory.core.IdempotentRequestOptions;
import com.basistheory.core.RequestOptions;
import com.basistheory.resources.tenants.members.requests.MembersListRequest;
import com.basistheory.resources.tenants.members.requests.UpdateTenantMemberRequest;
import com.basistheory.types.TenantMemberResponse;
import com.basistheory.types.TenantMemberResponsePaginatedList;

public class MembersClient {
    protected final ClientOptions clientOptions;

    private final RawMembersClient rawClient;

    public MembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMembersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMembersClient withRawResponse() {
        return this.rawClient;
    }

    public TenantMemberResponsePaginatedList list() {
        return this.rawClient.list().body();
    }

    public TenantMemberResponsePaginatedList list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    public TenantMemberResponsePaginatedList list(MembersListRequest request) {
        return this.rawClient.list(request).body();
    }

    public TenantMemberResponsePaginatedList list(MembersListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    public TenantMemberResponse update(String memberId, UpdateTenantMemberRequest request) {
        return this.rawClient.update(memberId, request).body();
    }

    public TenantMemberResponse update(
            String memberId, UpdateTenantMemberRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.update(memberId, request, requestOptions).body();
    }

    public void delete(String memberId) {
        this.rawClient.delete(memberId).body();
    }

    public void delete(String memberId, RequestOptions requestOptions) {
        this.rawClient.delete(memberId, requestOptions).body();
    }
}
