/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.basistheory.resources.tokens.requests;

import com.basistheory.core.ObjectMappers;
import com.basistheory.types.UpdatePrivacy;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateTokenRequest.Builder.class)
public final class UpdateTokenRequest {
    private final Optional<Object> data;

    private final Optional<UpdatePrivacy> privacy;

    private final Optional<Map<String, Optional<String>>> metadata;

    private final Optional<List<String>> searchIndexes;

    private final Optional<String> fingerprintExpression;

    private final Optional<Object> mask;

    private final Optional<String> expiresAt;

    private final Optional<Boolean> deduplicateToken;

    private final Optional<List<String>> containers;

    private final Map<String, Object> additionalProperties;

    private UpdateTokenRequest(
            Optional<Object> data,
            Optional<UpdatePrivacy> privacy,
            Optional<Map<String, Optional<String>>> metadata,
            Optional<List<String>> searchIndexes,
            Optional<String> fingerprintExpression,
            Optional<Object> mask,
            Optional<String> expiresAt,
            Optional<Boolean> deduplicateToken,
            Optional<List<String>> containers,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.privacy = privacy;
        this.metadata = metadata;
        this.searchIndexes = searchIndexes;
        this.fingerprintExpression = fingerprintExpression;
        this.mask = mask;
        this.expiresAt = expiresAt;
        this.deduplicateToken = deduplicateToken;
        this.containers = containers;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public Optional<Object> getData() {
        return data;
    }

    @JsonProperty("privacy")
    public Optional<UpdatePrivacy> getPrivacy() {
        return privacy;
    }

    @JsonProperty("metadata")
    public Optional<Map<String, Optional<String>>> getMetadata() {
        return metadata;
    }

    @JsonProperty("search_indexes")
    public Optional<List<String>> getSearchIndexes() {
        return searchIndexes;
    }

    @JsonProperty("fingerprint_expression")
    public Optional<String> getFingerprintExpression() {
        return fingerprintExpression;
    }

    @JsonProperty("mask")
    public Optional<Object> getMask() {
        return mask;
    }

    @JsonProperty("expires_at")
    public Optional<String> getExpiresAt() {
        return expiresAt;
    }

    @JsonProperty("deduplicate_token")
    public Optional<Boolean> getDeduplicateToken() {
        return deduplicateToken;
    }

    @JsonProperty("containers")
    public Optional<List<String>> getContainers() {
        return containers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateTokenRequest && equalTo((UpdateTokenRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateTokenRequest other) {
        return data.equals(other.data)
                && privacy.equals(other.privacy)
                && metadata.equals(other.metadata)
                && searchIndexes.equals(other.searchIndexes)
                && fingerprintExpression.equals(other.fingerprintExpression)
                && mask.equals(other.mask)
                && expiresAt.equals(other.expiresAt)
                && deduplicateToken.equals(other.deduplicateToken)
                && containers.equals(other.containers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.data,
                this.privacy,
                this.metadata,
                this.searchIndexes,
                this.fingerprintExpression,
                this.mask,
                this.expiresAt,
                this.deduplicateToken,
                this.containers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> data = Optional.empty();

        private Optional<UpdatePrivacy> privacy = Optional.empty();

        private Optional<Map<String, Optional<String>>> metadata = Optional.empty();

        private Optional<List<String>> searchIndexes = Optional.empty();

        private Optional<String> fingerprintExpression = Optional.empty();

        private Optional<Object> mask = Optional.empty();

        private Optional<String> expiresAt = Optional.empty();

        private Optional<Boolean> deduplicateToken = Optional.empty();

        private Optional<List<String>> containers = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateTokenRequest other) {
            data(other.getData());
            privacy(other.getPrivacy());
            metadata(other.getMetadata());
            searchIndexes(other.getSearchIndexes());
            fingerprintExpression(other.getFingerprintExpression());
            mask(other.getMask());
            expiresAt(other.getExpiresAt());
            deduplicateToken(other.getDeduplicateToken());
            containers(other.getContainers());
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<Object> data) {
            this.data = data;
            return this;
        }

        public Builder data(Object data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        @JsonSetter(value = "privacy", nulls = Nulls.SKIP)
        public Builder privacy(Optional<UpdatePrivacy> privacy) {
            this.privacy = privacy;
            return this;
        }

        public Builder privacy(UpdatePrivacy privacy) {
            this.privacy = Optional.ofNullable(privacy);
            return this;
        }

        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, Optional<String>>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, Optional<String>> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @JsonSetter(value = "search_indexes", nulls = Nulls.SKIP)
        public Builder searchIndexes(Optional<List<String>> searchIndexes) {
            this.searchIndexes = searchIndexes;
            return this;
        }

        public Builder searchIndexes(List<String> searchIndexes) {
            this.searchIndexes = Optional.ofNullable(searchIndexes);
            return this;
        }

        @JsonSetter(value = "fingerprint_expression", nulls = Nulls.SKIP)
        public Builder fingerprintExpression(Optional<String> fingerprintExpression) {
            this.fingerprintExpression = fingerprintExpression;
            return this;
        }

        public Builder fingerprintExpression(String fingerprintExpression) {
            this.fingerprintExpression = Optional.ofNullable(fingerprintExpression);
            return this;
        }

        @JsonSetter(value = "mask", nulls = Nulls.SKIP)
        public Builder mask(Optional<Object> mask) {
            this.mask = mask;
            return this;
        }

        public Builder mask(Object mask) {
            this.mask = Optional.ofNullable(mask);
            return this;
        }

        @JsonSetter(value = "expires_at", nulls = Nulls.SKIP)
        public Builder expiresAt(Optional<String> expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        public Builder expiresAt(String expiresAt) {
            this.expiresAt = Optional.ofNullable(expiresAt);
            return this;
        }

        @JsonSetter(value = "deduplicate_token", nulls = Nulls.SKIP)
        public Builder deduplicateToken(Optional<Boolean> deduplicateToken) {
            this.deduplicateToken = deduplicateToken;
            return this;
        }

        public Builder deduplicateToken(Boolean deduplicateToken) {
            this.deduplicateToken = Optional.ofNullable(deduplicateToken);
            return this;
        }

        @JsonSetter(value = "containers", nulls = Nulls.SKIP)
        public Builder containers(Optional<List<String>> containers) {
            this.containers = containers;
            return this;
        }

        public Builder containers(List<String> containers) {
            this.containers = Optional.ofNullable(containers);
            return this;
        }

        public UpdateTokenRequest build() {
            return new UpdateTokenRequest(
                    data,
                    privacy,
                    metadata,
                    searchIndexes,
                    fingerprintExpression,
                    mask,
                    expiresAt,
                    deduplicateToken,
                    containers,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
